-- INNER JOIN 사용
SELECT  CART_ID
FROM (
    SELECT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
    ) A
JOIN 
    (SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS 
    WHERE NAME =  'Milk'
    ) B
    USING (CART_ID)


-- HAVING 사용
SELECT CART_ID
FROM CART_PRODUCTS 
WHERE NAME IN ('Yogurt', 'Milk')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) = 2
