-- 코드 입력
WITH RECURSIVE num_hour(HOUR) AS (
	SELECT 0
    UNION ALL 
    SELECT HOUR + 1 
    FROM num_hour
    WHERE HOUR < 23
	)
SELECT A.HOUR, IFNULL(cnt,0)
FROM num_hour A
LEFT JOIN(
    SELECT HOUR(DATETIME) AS HOUR, COUNT(HOUR(DATETIME)) AS cnt
    FROM ANIMAL_OUTS
    GROUP BY 1
    ) B
ON A.HOUR = B.HOUR