-- 내 풀이
SELECT A.ID, A.NAME, HOST_ID
FROM PLACES A
JOIN(
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID)>=2
    ) B
    USING (HOST_ID)
ORDER BY A.ID


-- xx0hn님의 풀이
SELECT ID, NAME, HOST_ID
FROM PLACES A
WHERE (SELECT COUNT(HOST_ID) AS count
      FROM PLACES B
      WHERE A.HOST_ID=B.HOST_ID) >1;