SELECT  ROUND(AVG(LAT_N),4)
FROM(SELECT LAT_N,
            RANK()OVER(ORDER BY LAT_N) AS rank_LAT
     FROM STATION
     ) foo 
WHERE 
    rank_LAT = (SELECT CEIL((COUNT(*)+1)*0.5) FROM STATION) OR
    rank_LAT = (SELECT FLOOR((COUNT(*)+1)*0.5) FROM STATION)